/**
 * The skill/role knowledge base behind every ranking decision.
 *
 * This replaces what an embedding model used to supply implicitly: the fact
 * that "React" implies JSX and Redux and *not* Kubernetes. Writing it out by
 * hand costs a few hundred lines but buys something the embeddings never had —
 * when a search ranks badly you can open this file and see exactly why, and a
 * contributor can fix it in a pull request.
 *
 * Term roles:
 *   aliases  — query spellings that resolve to this entry
 *   strong   — near-proof that a posting is this role
 *   related  — supporting evidence, weaker on its own
 *   negative — evidence the posting is a *different* role
 */
import type { JobCategory } from "@/lib/scrapers/types";

export interface TaxonomyEntry {
  id: string;
  label: string;
  category: JobCategory;
  aliases: string[];
  strong: string[];
  related: string[];
  negative: string[];
  includedTitles: string[];
  excludedTitles: string[];
  canonicalText: string;
  scrapingKeyword: string;
}

/** Applied to every frontend-ish entry so the shared exclusions stay in sync. */
const BACKEND_NEG = ["backend", "server-side", "microservice", "kubernetes", "devops"];
const FRONTEND_NEG = ["frontend", "css", "ui design", "figma"];
const MOBILE_NEG = ["ios", "android", "swift", "kotlin", "react-native", "flutter"];

export const TAXONOMY_DATA: TaxonomyEntry[] = [
  // ── Frontend ───────────────────────────────────────────────────────────────
  {
    id: "react", label: "React", category: "Frontend",
    aliases: ["react", "react.js", "reactjs", "react js", "next.js", "nextjs", "next js", "remix"],
    strong: ["react", "jsx", "hooks", "redux", "next.js", "react query", "zustand"],
    related: ["frontend", "javascript", "typescript", "spa", "component", "webpack", "vite", "tailwind", "css", "html"],
    negative: [...BACKEND_NEG, ...MOBILE_NEG, "php", "java", ".net", "data engineer"],
    includedTitles: ["react developer", "frontend developer", "front-end developer", "ui developer", "javascript developer", "typescript developer", "web developer"],
    excludedTitles: ["backend", "fullstack", "devops", "qa", "ios", "android", "data engineer", "java developer", "php developer", ".net developer", "it director", "sales"],
    canonicalText: "React frontend developer building single-page applications with JavaScript and TypeScript, React hooks, Redux or Context state management, Next.js, reusable UI component libraries, responsive CSS and REST/GraphQL API integration.",
    scrapingKeyword: "React",
  },
  {
    id: "vue", label: "Vue", category: "Frontend",
    aliases: ["vue", "vue.js", "vuejs", "vue js", "nuxt", "nuxt.js", "nuxtjs"],
    strong: ["vue", "vuex", "pinia", "nuxt", "composition api"],
    related: ["frontend", "javascript", "typescript", "spa", "component", "css", "html"],
    negative: [...BACKEND_NEG, ...MOBILE_NEG, "react", "angular"],
    includedTitles: ["vue developer", "frontend developer", "ui developer", "javascript developer"],
    excludedTitles: ["backend", "devops", "qa", "ios", "android", "data engineer"],
    canonicalText: "Vue.js frontend developer working with Vue 3 Composition API, Pinia or Vuex state management, Nuxt, TypeScript, and responsive component-driven web interfaces.",
    scrapingKeyword: "Vue",
  },
  {
    id: "angular", label: "Angular", category: "Frontend",
    aliases: ["angular", "angularjs", "angular.js"],
    strong: ["angular", "rxjs", "ngrx", "typescript"],
    related: ["frontend", "javascript", "spa", "component", "css", "html"],
    negative: [...BACKEND_NEG, ...MOBILE_NEG, "react", "vue"],
    includedTitles: ["angular developer", "frontend developer", "ui developer", "typescript developer"],
    excludedTitles: ["backend", "devops", "qa", "ios", "android", "data engineer"],
    canonicalText: "Angular frontend developer using modern Angular with TypeScript, RxJS observables, NgRx state management and component architecture for single-page applications.",
    scrapingKeyword: "Angular",
  },
  {
    id: "svelte", label: "Svelte", category: "Frontend",
    aliases: ["svelte", "sveltekit", "svelte.js"],
    strong: ["svelte", "sveltekit"],
    related: ["frontend", "javascript", "typescript", "spa", "component", "css"],
    negative: [...BACKEND_NEG, ...MOBILE_NEG],
    includedTitles: ["svelte developer", "frontend developer", "javascript developer"],
    excludedTitles: ["backend", "devops", "qa", "ios", "android"],
    canonicalText: "Svelte and SvelteKit frontend developer building compiled, reactive web interfaces with TypeScript and modern CSS.",
    scrapingKeyword: "Svelte",
  },
  {
    id: "frontend", label: "Frontend", category: "Frontend",
    aliases: ["frontend", "front-end", "front end", "ui developer", "web developer", "webdeveloper"],
    strong: ["frontend", "react", "vue", "angular", "css", "html", "javascript"],
    related: ["typescript", "spa", "component", "responsive", "accessibility", "sass", "tailwind", "webpack", "vite", "figma"],
    negative: [...BACKEND_NEG, ...MOBILE_NEG, "php", "java", ".net", "data engineer"],
    includedTitles: ["frontend developer", "front-end developer", "ui developer", "react developer", "vue developer", "angular developer", "javascript developer", "web developer"],
    excludedTitles: ["backend", "devops", "qa", "ios", "android", "data engineer", "it director", "sales", "recruiter"],
    canonicalText: "Frontend web developer implementing user interfaces with React, Vue or Angular, HTML, CSS and JavaScript or TypeScript, focusing on responsive design, accessibility and component libraries.",
    scrapingKeyword: "frontend",
  },
  {
    id: "javascript", label: "JavaScript", category: "Frontend",
    aliases: ["javascript", "js", "ecmascript"],
    strong: ["javascript", "es6", "typescript", "node.js"],
    related: ["frontend", "react", "vue", "angular", "web", "browser", "npm"],
    negative: ["java developer", "php", ".net", "kubernetes"],
    includedTitles: ["javascript developer", "frontend developer", "fullstack developer", "web developer"],
    excludedTitles: ["java developer", "devops", "data engineer", "qa"],
    canonicalText: "JavaScript developer working across modern ECMAScript, browser APIs, Node.js tooling and popular frontend frameworks.",
    scrapingKeyword: "JavaScript",
  },
  {
    id: "typescript", label: "TypeScript", category: "Frontend",
    aliases: ["typescript", "ts"],
    strong: ["typescript", "type safety", "javascript"],
    related: ["react", "node.js", "frontend", "fullstack", "eslint"],
    negative: ["php", "java developer", ".net"],
    includedTitles: ["typescript developer", "frontend developer", "fullstack developer", "node.js developer"],
    excludedTitles: ["devops", "data engineer", "qa"],
    canonicalText: "TypeScript developer writing strongly typed application code across frontend frameworks and Node.js services.",
    scrapingKeyword: "TypeScript",
  },

  // ── Backend ────────────────────────────────────────────────────────────────
  {
    id: "backend", label: "Backend", category: "Backend",
    aliases: ["backend", "back-end", "back end", "server-side", "api developer"],
    strong: ["backend", "api", "rest", "graphql", "database", "sql", "microservice"],
    related: ["node.js", "python", "java", "go", "postgresql", "redis", "docker", "authentication", "scalability"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG, "ux", "graphic design"],
    includedTitles: ["backend developer", "back-end developer", "software engineer", "api developer", "node.js developer", "python developer", "java developer", "go developer"],
    excludedTitles: ["frontend", "ui developer", "ios", "android", "graphic designer", "qa engineer", "recruiter"],
    canonicalText: "Backend software engineer designing REST and GraphQL APIs, relational and document databases, microservices, caching, authentication and scalable server-side systems.",
    scrapingKeyword: "backend",
  },
  {
    id: "node", label: "Node.js", category: "Backend",
    aliases: ["node", "node.js", "nodejs", "node js", "express", "nestjs", "nest.js"],
    strong: ["node.js", "express", "nestjs", "fastify", "typescript"],
    related: ["backend", "api", "rest", "graphql", "postgresql", "mongodb", "redis", "javascript", "microservice"],
    negative: [...FRONTEND_NEG, "php", "java developer", ".net", "ios", "android"],
    includedTitles: ["node.js developer", "backend developer", "javascript developer", "typescript developer", "fullstack developer"],
    excludedTitles: ["frontend only", "ios", "android", "devops", "qa"],
    canonicalText: "Node.js backend developer building services with Express, NestJS or Fastify in TypeScript, backed by PostgreSQL, MongoDB and Redis, deployed as containers.",
    scrapingKeyword: "node.js",
  },
  {
    id: "python", label: "Python", category: "Backend",
    aliases: ["python", "django", "flask", "fastapi"],
    strong: ["python", "django", "fastapi", "flask", "pytest"],
    related: ["backend", "api", "rest", "postgresql", "celery", "pandas", "docker", "sql"],
    negative: [...FRONTEND_NEG, "php", "java developer", ".net", "ios", "android"],
    includedTitles: ["python developer", "backend developer", "software engineer", "django developer"],
    excludedTitles: ["frontend", "ios", "android", "qa engineer"],
    canonicalText: "Python backend developer building web services with Django, FastAPI or Flask, PostgreSQL, asynchronous task queues, and automated testing.",
    scrapingKeyword: "python",
  },
  {
    id: "java", label: "Java", category: "Backend",
    aliases: ["java", "spring", "spring boot", "springboot", "kotlin backend"],
    strong: ["java", "spring", "spring boot", "hibernate", "jvm", "maven"],
    related: ["backend", "api", "rest", "microservice", "sql", "kafka", "junit", "gradle"],
    negative: [...FRONTEND_NEG, "javascript developer", "php", "ios", "android"],
    includedTitles: ["java developer", "backend developer", "software engineer", "spring developer"],
    excludedTitles: ["frontend", "javascript developer", "android developer", "qa"],
    canonicalText: "Java backend engineer building Spring Boot services on the JVM with Hibernate, relational databases, Kafka messaging and microservice architecture.",
    scrapingKeyword: "Java",
  },
  {
    id: "dotnet", label: ".NET / C#", category: "Backend",
    aliases: [".net", "dotnet", "c#", "csharp", "asp.net", "aspnet", "net developer"],
    strong: [".net", "c#", "asp.net", "entity framework", "blazor"],
    related: ["backend", "api", "rest", "sql server", "azure", "microservice"],
    negative: [...FRONTEND_NEG, "java developer", "php", "python"],
    includedTitles: [".net developer", "c# developer", "backend developer", "software engineer"],
    excludedTitles: ["frontend", "java developer", "php developer", "qa"],
    canonicalText: ".NET backend developer building ASP.NET Core services in C# with Entity Framework, SQL Server and Azure cloud infrastructure.",
    scrapingKeyword: ".NET",
  },
  {
    id: "php", label: "PHP", category: "Backend",
    aliases: ["php", "laravel", "symfony", "wordpress"],
    strong: ["php", "laravel", "symfony", "composer"],
    related: ["backend", "mysql", "api", "rest", "wordpress", "web"],
    negative: ["java developer", ".net", "python", "ios", "android", "devops"],
    includedTitles: ["php developer", "laravel developer", "backend developer", "web developer"],
    excludedTitles: ["frontend only", "java developer", ".net developer", "qa"],
    canonicalText: "PHP backend developer working with Laravel or Symfony, MySQL, REST APIs and content-driven web applications.",
    scrapingKeyword: "PHP",
  },
  {
    id: "go", label: "Go", category: "Backend",
    aliases: ["go", "golang", "go lang"],
    strong: ["golang", "goroutine", "grpc"],
    related: ["backend", "api", "microservice", "kubernetes", "docker", "postgresql", "concurrency"],
    negative: [...FRONTEND_NEG, "php", "java developer", ".net"],
    includedTitles: ["go developer", "golang developer", "backend developer", "software engineer"],
    excludedTitles: ["frontend", "qa", "ios", "android"],
    canonicalText: "Go backend engineer building high-throughput microservices with goroutines, gRPC and containerised deployment.",
    scrapingKeyword: "Golang",
  },
  {
    id: "rust", label: "Rust", category: "Backend",
    aliases: ["rust", "rustlang"],
    strong: ["rust", "cargo", "tokio", "memory safety"],
    related: ["backend", "systems", "performance", "wasm", "grpc", "concurrency"],
    negative: [...FRONTEND_NEG, "php", "wordpress"],
    includedTitles: ["rust developer", "systems engineer", "backend developer", "software engineer"],
    excludedTitles: ["frontend", "qa", "support"],
    canonicalText: "Rust engineer building memory-safe, high-performance systems and services with Cargo, async Tokio runtimes and WebAssembly targets.",
    scrapingKeyword: "Rust",
  },
  {
    id: "ruby", label: "Ruby", category: "Backend",
    aliases: ["ruby", "rails", "ruby on rails", "ror"],
    strong: ["ruby", "rails", "rspec", "sidekiq"],
    related: ["backend", "api", "rest", "postgresql", "web"],
    negative: [...FRONTEND_NEG, "php", "java developer", ".net"],
    includedTitles: ["ruby developer", "rails developer", "backend developer", "software engineer"],
    excludedTitles: ["frontend", "qa", "ios"],
    canonicalText: "Ruby on Rails developer building web applications and APIs with ActiveRecord, RSpec testing and background job processing.",
    scrapingKeyword: "Ruby",
  },
  {
    id: "scala", label: "Scala", category: "Backend",
    aliases: ["scala", "akka"],
    strong: ["scala", "akka", "spark", "functional programming"],
    related: ["backend", "jvm", "kafka", "microservice", "data"],
    negative: [...FRONTEND_NEG, "php", "wordpress"],
    includedTitles: ["scala developer", "backend developer", "data engineer", "software engineer"],
    excludedTitles: ["frontend", "qa", "support"],
    canonicalText: "Scala engineer building functional, concurrent JVM systems with Akka, Spark and Kafka streaming pipelines.",
    scrapingKeyword: "Scala",
  },
  {
    id: "elixir", label: "Elixir", category: "Backend",
    aliases: ["elixir", "phoenix framework", "erlang"],
    strong: ["elixir", "phoenix", "erlang", "otp"],
    related: ["backend", "api", "concurrency", "postgresql", "realtime"],
    negative: [...FRONTEND_NEG, "php", "java developer"],
    includedTitles: ["elixir developer", "backend developer", "software engineer"],
    excludedTitles: ["frontend", "qa"],
    canonicalText: "Elixir engineer building fault-tolerant concurrent services on the BEAM with Phoenix, OTP supervision trees and real-time channels.",
    scrapingKeyword: "Elixir",
  },
  {
    id: "fullstack", label: "Fullstack", category: "Fullstack",
    aliases: ["fullstack", "full-stack", "full stack", "fullstack developer"],
    strong: ["fullstack", "frontend", "backend", "react", "node.js", "api"],
    related: ["typescript", "javascript", "postgresql", "rest", "graphql", "docker", "css", "python"],
    negative: ["devops only", "qa only", "graphic design", "recruiter"],
    includedTitles: ["fullstack developer", "full-stack developer", "software engineer", "web developer", "frontend developer", "backend developer"],
    excludedTitles: ["devops engineer", "qa engineer", "data engineer", "graphic designer", "recruiter", "sales"],
    canonicalText: "Fullstack developer owning features end to end: React or Vue interfaces, Node.js or Python services, relational databases, REST and GraphQL APIs and cloud deployment.",
    scrapingKeyword: "fullstack",
  },

  // ── Infrastructure ─────────────────────────────────────────────────────────
  {
    id: "devops", label: "DevOps", category: "DevOps",
    aliases: ["devops", "dev ops", "sre", "site reliability", "platform engineer", "infrastructure"],
    strong: ["devops", "kubernetes", "terraform", "ci/cd", "docker", "ansible", "sre"],
    related: ["aws", "gcp", "azure", "prometheus", "grafana", "linux", "helm", "gitlab", "monitoring", "iac"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG, "feature development", "graphic design"],
    includedTitles: ["devops engineer", "sre", "site reliability engineer", "platform engineer", "cloud engineer", "infrastructure engineer"],
    excludedTitles: ["frontend", "ios", "android", "qa engineer", "data analyst", "graphic designer"],
    canonicalText: "DevOps and platform engineer running Kubernetes, Docker, Terraform infrastructure as code and CI/CD pipelines on AWS, GCP or Azure with Prometheus and Grafana observability.",
    scrapingKeyword: "devops",
  },
  {
    id: "cloud", label: "Cloud", category: "DevOps",
    aliases: ["cloud", "aws", "azure", "gcp", "cloud engineer"],
    strong: ["aws", "azure", "gcp", "cloud", "terraform", "lambda"],
    related: ["devops", "kubernetes", "docker", "serverless", "iam", "networking", "cost optimisation"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG],
    includedTitles: ["cloud engineer", "devops engineer", "cloud architect", "platform engineer"],
    excludedTitles: ["frontend", "ios", "android", "qa"],
    canonicalText: "Cloud engineer designing and operating AWS, Azure or GCP infrastructure with Terraform, serverless functions, networking and identity management.",
    scrapingKeyword: "cloud",
  },
  {
    id: "kubernetes", label: "Kubernetes", category: "DevOps",
    aliases: ["kubernetes", "k8s", "openshift", "helm"],
    strong: ["kubernetes", "k8s", "helm", "container", "docker"],
    related: ["devops", "terraform", "ci/cd", "istio", "prometheus", "linux", "aws"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG],
    includedTitles: ["kubernetes engineer", "devops engineer", "platform engineer", "sre"],
    excludedTitles: ["frontend", "ios", "android", "qa"],
    canonicalText: "Kubernetes platform engineer operating container orchestration, Helm charts, service meshes and cluster observability at scale.",
    scrapingKeyword: "kubernetes",
  },

  // ── Mobile ─────────────────────────────────────────────────────────────────
  {
    id: "mobile", label: "Mobile", category: "Mobile",
    aliases: ["mobile", "mobile developer", "app developer"],
    strong: ["mobile", "ios", "android", "react-native", "flutter", "app store"],
    related: ["swift", "kotlin", "objective-c", "dart", "push notification", "mobile ui"],
    negative: ["backend only", "devops", "data engineer", "web frontend only"],
    includedTitles: ["mobile developer", "ios developer", "android developer", "react native developer", "flutter developer"],
    excludedTitles: ["backend developer", "devops", "qa engineer", "data engineer"],
    canonicalText: "Mobile developer shipping iOS and Android applications, native or cross-platform, integrating REST APIs, push notifications and app-store release processes.",
    scrapingKeyword: "mobile",
  },
  {
    id: "ios", label: "iOS", category: "Mobile",
    aliases: ["ios", "swift", "swiftui", "objective-c", "iphone"],
    strong: ["ios", "swift", "swiftui", "uikit", "xcode", "objective-c"],
    related: ["mobile", "app store", "core data", "combine", "apple"],
    negative: ["android", "kotlin", "backend", "frontend web", "devops"],
    includedTitles: ["ios developer", "swift developer", "mobile developer"],
    excludedTitles: ["android", "flutter", "react native", "backend", "frontend", "devops", "qa"],
    canonicalText: "iOS developer building native applications in Swift with SwiftUI and UIKit, Xcode tooling, Core Data persistence and App Store distribution.",
    scrapingKeyword: "iOS",
  },
  {
    id: "android", label: "Android", category: "Mobile",
    aliases: ["android", "kotlin", "jetpack compose"],
    strong: ["android", "kotlin", "jetpack", "compose", "android studio"],
    related: ["mobile", "google play", "mvvm", "gradle", "java"],
    negative: ["ios", "swift", "backend", "frontend web", "devops"],
    includedTitles: ["android developer", "kotlin developer", "mobile developer"],
    excludedTitles: ["ios", "swift", "flutter", "backend", "frontend", "devops", "qa"],
    canonicalText: "Android developer building native applications in Kotlin with Jetpack Compose, MVVM architecture, Gradle builds and Google Play releases.",
    scrapingKeyword: "Android",
  },
  {
    id: "flutter", label: "Flutter", category: "Mobile",
    aliases: ["flutter", "dart"],
    strong: ["flutter", "dart", "cross-platform"],
    related: ["mobile", "ios", "android", "app store", "google play", "widget"],
    negative: ["backend", "frontend web", "devops", "data engineer"],
    includedTitles: ["flutter developer", "mobile developer", "cross-platform developer"],
    excludedTitles: ["backend", "devops", "qa", "data engineer"],
    canonicalText: "Flutter developer building cross-platform iOS and Android applications in Dart with a shared widget codebase.",
    scrapingKeyword: "Flutter",
  },
  {
    id: "react-native", label: "React Native", category: "Mobile",
    aliases: ["react native", "react-native", "reactnative"],
    strong: ["react-native", "react", "mobile", "expo"],
    related: ["javascript", "typescript", "ios", "android", "app store", "native module"],
    negative: ["backend", "devops", "data engineer", "php"],
    includedTitles: ["react native developer", "mobile developer", "javascript developer"],
    excludedTitles: ["backend", "devops", "qa", "data engineer"],
    canonicalText: "React Native developer shipping cross-platform mobile applications in TypeScript, bridging native modules and publishing to both app stores.",
    scrapingKeyword: "React Native",
  },

  // ── Data ───────────────────────────────────────────────────────────────────
  {
    id: "data-engineer", label: "Data Engineering", category: "Data",
    aliases: ["data engineer", "data engineering", "etl", "data pipeline"],
    strong: ["data engineer", "etl", "airflow", "spark", "data warehouse", "dbt"],
    related: ["python", "sql", "bigquery", "snowflake", "kafka", "pipeline", "redshift", "databricks"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG, "graphic design"],
    includedTitles: ["data engineer", "analytics engineer", "etl developer", "big data engineer"],
    excludedTitles: ["frontend", "ios", "android", "devops only", "qa", "graphic designer"],
    canonicalText: "Data engineer building ETL and ELT pipelines with Airflow, Spark and dbt into warehouses such as BigQuery, Snowflake or Redshift, modelling data for analytics.",
    scrapingKeyword: "data engineer",
  },
  {
    id: "data-analyst", label: "Data Analysis", category: "Data",
    aliases: ["data analyst", "analytics", "business intelligence", "bi analyst"],
    strong: ["data analyst", "sql", "tableau", "power bi", "looker", "dashboard"],
    related: ["excel", "python", "reporting", "kpi", "visualisation", "statistics"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG, "kubernetes"],
    includedTitles: ["data analyst", "business intelligence analyst", "bi developer", "analytics specialist"],
    excludedTitles: ["frontend", "backend developer", "devops", "ios", "android"],
    canonicalText: "Data analyst querying warehouses with SQL, building dashboards in Tableau, Power BI or Looker, and turning business questions into reportable metrics.",
    scrapingKeyword: "data analyst",
  },
  {
    id: "data-science", label: "Data Science", category: "Data",
    aliases: ["data scientist", "data science", "machine learning", "ml", "ml engineer", "ai engineer", "deep learning", "nlp"],
    strong: ["machine learning", "data scientist", "pytorch", "tensorflow", "model", "mlops"],
    related: ["python", "pandas", "numpy", "scikit-learn", "statistics", "feature engineering", "sql", "jupyter"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG, "wordpress"],
    includedTitles: ["data scientist", "machine learning engineer", "ml engineer", "ai engineer", "research engineer"],
    excludedTitles: ["frontend", "ios", "android", "qa", "support"],
    canonicalText: "Machine learning engineer and data scientist training and deploying models with PyTorch or TensorFlow, feature engineering in Python, and MLOps pipelines for production inference.",
    scrapingKeyword: "machine learning",
  },
  {
    id: "database", label: "Databases", category: "Data",
    aliases: ["dba", "database administrator", "sql developer", "postgresql", "mysql", "oracle"],
    strong: ["database", "postgresql", "mysql", "oracle", "sql server", "dba", "replication"],
    related: ["sql", "indexing", "query optimisation", "backup", "migration", "performance"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG],
    includedTitles: ["database administrator", "dba", "sql developer", "database engineer"],
    excludedTitles: ["frontend", "ios", "android", "graphic designer"],
    canonicalText: "Database engineer administering PostgreSQL, MySQL or SQL Server: schema design, indexing, query optimisation, replication and backup strategy.",
    scrapingKeyword: "database",
  },

  // ── Quality & security ─────────────────────────────────────────────────────
  {
    id: "qa", label: "QA", category: "QA",
    aliases: ["qa", "quality assurance", "tester", "test engineer", "sdet", "testing"],
    strong: ["qa", "testing", "test automation", "selenium", "cypress", "playwright", "sdet"],
    related: ["jira", "regression", "test case", "bug", "e2e", "unit test", "ci/cd", "postman"],
    negative: ["frontend developer", "backend developer", "devops engineer", "data engineer"],
    includedTitles: ["qa engineer", "test engineer", "sdet", "automation engineer", "qa analyst", "test automation engineer"],
    excludedTitles: ["frontend developer", "backend developer", "devops", "data engineer", "designer"],
    canonicalText: "QA engineer designing test strategy and automating regression suites with Selenium, Cypress or Playwright, integrated into CI pipelines and tracked in Jira.",
    scrapingKeyword: "QA",
  },
  {
    id: "security", label: "Security", category: "Security",
    aliases: ["security", "cybersecurity", "infosec", "penetration tester", "pentester", "appsec", "soc analyst"],
    strong: ["security", "penetration testing", "vulnerability", "owasp", "siem", "incident response"],
    related: ["compliance", "iso 27001", "threat", "encryption", "audit", "firewall", "soc", "risk"],
    negative: [...FRONTEND_NEG, ...MOBILE_NEG, "graphic design"],
    includedTitles: ["security engineer", "security analyst", "penetration tester", "application security engineer", "soc analyst", "security architect"],
    excludedTitles: ["frontend", "ios", "android", "graphic designer", "sales"],
    canonicalText: "Security engineer running vulnerability assessments and penetration tests, hardening applications against OWASP risks, monitoring SIEM alerts and driving incident response.",
    scrapingKeyword: "security",
  },

  // ── Design & product ───────────────────────────────────────────────────────
  {
    id: "design", label: "Design", category: "Design",
    aliases: ["ux", "ui", "ux designer", "ui designer", "product designer", "ux/ui", "graphic designer"],
    strong: ["ux", "ui design", "figma", "prototype", "wireframe", "user research"],
    related: ["design system", "accessibility", "sketch", "usability", "interaction", "visual design"],
    negative: ["backend", "kubernetes", "devops", "data engineer", "database"],
    includedTitles: ["ux designer", "ui designer", "product designer", "ux/ui designer", "graphic designer"],
    excludedTitles: ["backend developer", "devops", "data engineer", "qa engineer"],
    canonicalText: "Product designer running user research, wireframes and high-fidelity prototypes in Figma, maintaining design systems and accessible interaction patterns.",
    scrapingKeyword: "designer",
  },
  {
    id: "product", label: "Product Management", category: "Product",
    aliases: ["product manager", "product owner", "po", "pm", "product management"],
    strong: ["product manager", "product owner", "roadmap", "backlog", "stakeholder"],
    related: ["agile", "scrum", "user story", "kpi", "discovery", "prioritisation", "jira"],
    negative: ["kubernetes", "css", "unit test", "soldering"],
    includedTitles: ["product manager", "product owner", "technical product manager"],
    excludedTitles: ["developer", "engineer", "designer", "qa"],
    canonicalText: "Product manager owning roadmap and backlog, running discovery with users and stakeholders, and prioritising delivery against measurable outcomes.",
    scrapingKeyword: "product manager",
  },
  {
    id: "project", label: "Project Management", category: "Product",
    aliases: ["project manager", "scrum master", "delivery manager", "agile coach"],
    strong: ["project manager", "scrum master", "delivery", "agile", "sprint"],
    related: ["stakeholder", "budget", "risk", "jira", "kanban", "reporting", "planning"],
    negative: ["kubernetes", "css", "unit test"],
    includedTitles: ["project manager", "scrum master", "delivery manager", "programme manager"],
    excludedTitles: ["developer", "engineer", "designer"],
    canonicalText: "Project or delivery manager coordinating agile teams, sprint planning, stakeholder communication, risk tracking and budget reporting.",
    scrapingKeyword: "project manager",
  },
  {
    id: "business-analyst", label: "Business Analysis", category: "Product",
    aliases: ["business analyst", "ba", "systems analyst", "requirements analyst"],
    strong: ["business analyst", "requirements", "process", "specification"],
    related: ["stakeholder", "documentation", "uml", "workflow", "sql", "jira"],
    negative: ["kubernetes", "css", "unit test"],
    includedTitles: ["business analyst", "systems analyst", "requirements engineer"],
    excludedTitles: ["developer", "devops", "designer"],
    canonicalText: "Business analyst eliciting and documenting requirements, mapping business processes and translating them into system specifications for delivery teams.",
    scrapingKeyword: "business analyst",
  },

  // ── Specialist ─────────────────────────────────────────────────────────────
  {
    id: "embedded", label: "Embedded", category: "Backend",
    aliases: ["embedded", "firmware", "iot", "rtos", "embedded c"],
    strong: ["embedded", "firmware", "microcontroller", "rtos", "c++", "hardware"],
    related: ["arm", "iot", "driver", "linux kernel", "can bus", "sensor", "electronics"],
    negative: [...FRONTEND_NEG, "wordpress", "marketing"],
    includedTitles: ["embedded developer", "firmware engineer", "embedded software engineer", "iot engineer"],
    excludedTitles: ["frontend", "web developer", "marketing", "qa analyst"],
    canonicalText: "Embedded software engineer writing firmware in C and C++ for microcontrollers and RTOS targets, device drivers, and IoT connectivity.",
    scrapingKeyword: "embedded",
  },
  {
    id: "gamedev", label: "Game Development", category: "Other",
    aliases: ["game developer", "gamedev", "unity", "unreal", "game programmer"],
    strong: ["unity", "unreal", "game", "c++", "c#", "gameplay"],
    related: ["3d", "shader", "physics", "rendering", "animation", "engine"],
    negative: ["accounting", "recruiter", "devops"],
    includedTitles: ["game developer", "unity developer", "unreal developer", "gameplay programmer"],
    excludedTitles: ["devops", "data analyst", "recruiter"],
    canonicalText: "Game developer building gameplay systems in Unity or Unreal with C# or C++, working across rendering, physics and animation pipelines.",
    scrapingKeyword: "game developer",
  },
  {
    id: "salesforce", label: "Salesforce", category: "Other",
    aliases: ["salesforce", "apex", "crm developer"],
    strong: ["salesforce", "apex", "lightning", "crm"],
    related: ["integration", "workflow", "administrator", "visualforce", "soql"],
    negative: ["kubernetes", "game", "embedded"],
    includedTitles: ["salesforce developer", "salesforce administrator", "crm developer"],
    excludedTitles: ["frontend", "devops", "data engineer"],
    canonicalText: "Salesforce developer customising the platform with Apex, Lightning components and declarative automation, integrating CRM data with external systems.",
    scrapingKeyword: "Salesforce",
  },
  {
    id: "sap", label: "SAP", category: "Other",
    aliases: ["sap", "abap", "sap consultant", "s/4hana"],
    strong: ["sap", "abap", "s/4hana", "erp"],
    related: ["fiori", "hana", "module", "consultant", "integration"],
    negative: ["kubernetes", "game", "frontend"],
    includedTitles: ["sap consultant", "abap developer", "sap developer"],
    excludedTitles: ["frontend", "devops", "qa"],
    canonicalText: "SAP consultant and ABAP developer configuring and extending S/4HANA ERP modules, Fiori interfaces and integrations.",
    scrapingKeyword: "SAP",
  },
  {
    id: "support", label: "Technical Support", category: "Other",
    aliases: ["support", "helpdesk", "help desk", "technical support", "it support", "service desk"],
    strong: ["support", "helpdesk", "ticket", "troubleshoot", "service desk"],
    related: ["customer", "sla", "incident", "windows", "hardware", "onboarding", "jira"],
    negative: ["kubernetes", "machine learning", "figma"],
    includedTitles: ["technical support engineer", "it support specialist", "helpdesk technician", "service desk analyst"],
    excludedTitles: ["software engineer", "devops", "data scientist"],
    canonicalText: "Technical support engineer resolving user incidents against SLAs, triaging tickets, troubleshooting hardware and software, and escalating to engineering.",
    scrapingKeyword: "technical support",
  },
];
