/**
 * Raw country dataset.
 *
 * Split out of `countries.ts` purely so the accessor layer stays readable —
 * import from `./countries` (or `./index`) rather than from here, because the
 * accessors freeze the entries and build the lookup indexes.
 *
 * Coverage rule: every country with a meaningful IT job market, plus every
 * EU/EEA member, so board selection never has to fall back to "unknown".
 * Cities are lowercase and include the local spelling next to the English one
 * ("praha" and "prague") because listings use whichever the board speaks.
 * A city shared by two countries in this list is deliberately dropped from
 * both — `countryFromLocationText` refuses to guess between them.
 */
import type { CountryInfo } from "./countries";

export const COUNTRY_DATA: readonly CountryInfo[] = [
  // ─── Europe ────────────────────────────────────────────────────────────────
  { code: "AT", name: "Austria", currency: "EUR", region: "Europe",
    aliases: ["osterreich", "österreich", "republic of austria"],
    languages: ["de", "en"],
    cities: ["vienna", "wien", "graz", "linz", "salzburg", "innsbruck", "klagenfurt"] },
  { code: "BE", name: "Belgium", currency: "EUR", region: "Europe",
    aliases: ["belgie", "belgië", "belgique", "belgien"],
    languages: ["nl", "fr", "en"],
    cities: ["brussels", "brussel", "bruxelles", "antwerp", "antwerpen", "ghent", "gent", "leuven", "liege", "bruges", "charleroi"] },
  { code: "BG", name: "Bulgaria", currency: "BGN", region: "Europe",
    aliases: ["balgariya", "republic of bulgaria"],
    languages: ["bg", "en"],
    cities: ["sofia", "plovdiv", "varna", "burgas", "ruse", "stara zagora"] },
  { code: "CH", name: "Switzerland", currency: "CHF", region: "Europe",
    aliases: ["schweiz", "suisse", "svizzera", "helvetia"],
    languages: ["de", "fr", "it", "en"],
    cities: ["zurich", "zürich", "geneva", "geneve", "basel", "bern", "lausanne", "zug", "lugano", "winterthur"] },
  { code: "CY", name: "Cyprus", currency: "EUR", region: "Europe",
    aliases: ["kypros", "kibris", "republic of cyprus"],
    languages: ["el", "en"],
    cities: ["nicosia", "limassol", "larnaca", "paphos", "famagusta"] },
  { code: "CZ", name: "Czechia", currency: "CZK", region: "Europe",
    aliases: ["czech republic", "cesko", "česko", "ceska republika", "česká republika"],
    languages: ["cs", "en"],
    cities: ["prague", "praha", "brno", "ostrava", "plzen", "plzeň", "olomouc", "liberec", "hradec kralove", "ceske budejovice", "pardubice", "zlin"] },
  { code: "DE", name: "Germany", currency: "EUR", region: "Europe",
    aliases: ["deutschland", "federal republic of germany"],
    languages: ["de", "en"],
    cities: ["berlin", "munich", "münchen", "hamburg", "frankfurt", "cologne", "köln", "stuttgart", "düsseldorf", "leipzig", "dresden", "nuremberg"] },
  { code: "DK", name: "Denmark", currency: "DKK", region: "Europe",
    aliases: ["danmark"],
    languages: ["da", "en"],
    cities: ["copenhagen", "kobenhavn", "københavn", "aarhus", "odense", "aalborg", "esbjerg"] },
  { code: "EE", name: "Estonia", currency: "EUR", region: "Europe",
    aliases: ["eesti"],
    languages: ["et", "en"],
    cities: ["tallinn", "tartu", "narva", "parnu", "pärnu"] },
  { code: "ES", name: "Spain", currency: "EUR", region: "Europe",
    aliases: ["espana", "españa"],
    languages: ["es", "en"],
    cities: ["madrid", "barcelona", "valencia", "sevilla", "seville", "malaga", "málaga", "bilbao", "zaragoza", "alicante", "las palmas"] },
  { code: "FI", name: "Finland", currency: "EUR", region: "Europe",
    aliases: ["suomi"],
    languages: ["fi", "sv", "en"],
    cities: ["helsinki", "espoo", "tampere", "vantaa", "oulu", "turku", "jyvaskyla", "lahti"] },
  { code: "FR", name: "France", currency: "EUR", region: "Europe",
    aliases: ["french republic"],
    languages: ["fr", "en"],
    cities: ["paris", "lyon", "marseille", "toulouse", "bordeaux", "lille", "nantes", "strasbourg", "montpellier", "rennes", "grenoble", "sophia antipolis"] },
  { code: "GB", name: "United Kingdom", currency: "GBP", region: "Europe",
    aliases: ["uk", "great britain", "britain", "england", "scotland", "wales", "northern ireland"],
    languages: ["en"],
    cities: ["london", "manchester", "birmingham", "edinburgh", "glasgow", "bristol", "leeds", "cambridge", "oxford", "liverpool", "sheffield", "belfast"] },
  { code: "GR", name: "Greece", currency: "EUR", region: "Europe",
    aliases: ["hellas", "ellada", "hellenic republic"],
    languages: ["el", "en"],
    cities: ["athens", "thessaloniki", "patras", "heraklion", "larissa", "volos"] },
  { code: "HR", name: "Croatia", currency: "EUR", region: "Europe",
    aliases: ["hrvatska"],
    languages: ["hr", "en"],
    cities: ["zagreb", "rijeka", "osijek", "zadar", "dubrovnik", "varazdin"] },
  { code: "HU", name: "Hungary", currency: "HUF", region: "Europe",
    aliases: ["magyarorszag", "magyarország"],
    languages: ["hu", "en"],
    cities: ["budapest", "debrecen", "szeged", "miskolc", "pecs", "gyor", "györ"] },
  { code: "IE", name: "Ireland", currency: "EUR", region: "Europe",
    aliases: ["eire", "éire", "republic of ireland"],
    languages: ["en", "ga"],
    cities: ["dublin", "cork", "galway", "limerick", "waterford", "kilkenny"] },
  { code: "IS", name: "Iceland", currency: "ISK", region: "Europe",
    aliases: ["lydveldid island"],
    languages: ["is", "en"],
    cities: ["reykjavik", "reykjavík", "akureyri", "kopavogur", "hafnarfjordur"] },
  { code: "IT", name: "Italy", currency: "EUR", region: "Europe",
    aliases: ["italia", "italian republic"],
    languages: ["it", "en"],
    cities: ["rome", "roma", "milan", "milano", "turin", "torino", "naples", "napoli", "bologna", "florence", "firenze", "padova"] },
  { code: "LT", name: "Lithuania", currency: "EUR", region: "Europe",
    aliases: ["lietuva"],
    languages: ["lt", "en"],
    cities: ["vilnius", "kaunas", "klaipeda", "siauliai", "panevezys"] },
  { code: "LU", name: "Luxembourg", currency: "EUR", region: "Europe",
    aliases: ["letzebuerg", "grand duchy of luxembourg"],
    languages: ["fr", "de", "en"],
    cities: ["luxembourg city", "esch sur alzette", "differdange", "dudelange", "kirchberg"] },
  { code: "LV", name: "Latvia", currency: "EUR", region: "Europe",
    aliases: ["latvija"],
    languages: ["lv", "en"],
    cities: ["riga", "rīga", "daugavpils", "liepaja", "jurmala", "ventspils"] },
  { code: "MT", name: "Malta", currency: "EUR", region: "Europe",
    aliases: ["republic of malta"],
    languages: ["mt", "en"],
    cities: ["valletta", "sliema", "st julians", "birkirkara", "mosta"] },
  { code: "NL", name: "Netherlands", currency: "EUR", region: "Europe",
    aliases: ["holland", "nederland", "the netherlands"],
    languages: ["nl", "en"],
    cities: ["amsterdam", "rotterdam", "utrecht", "the hague", "den haag", "eindhoven", "groningen", "amersfoort", "delft"] },
  { code: "NO", name: "Norway", currency: "NOK", region: "Europe",
    aliases: ["norge", "noreg"],
    languages: ["nb", "en"],
    cities: ["oslo", "bergen", "trondheim", "stavanger", "tromso", "drammen", "kristiansand"] },
  { code: "PL", name: "Poland", currency: "PLN", region: "Europe",
    aliases: ["polska", "republic of poland"],
    languages: ["pl", "en"],
    cities: ["warsaw", "warszawa", "krakow", "kraków", "wroclaw", "wrocław", "poznan", "gdansk", "katowice", "lodz", "szczecin", "lublin"] },
  { code: "PT", name: "Portugal", currency: "EUR", region: "Europe",
    aliases: ["portuguese republic"],
    languages: ["pt", "en"],
    cities: ["lisbon", "lisboa", "porto", "braga", "coimbra", "aveiro", "faro", "funchal"] },
  { code: "RO", name: "Romania", currency: "RON", region: "Europe",
    aliases: ["românia", "rumunsko"],
    languages: ["ro", "en"],
    cities: ["bucharest", "bucuresti", "bucurești", "cluj napoca", "cluj", "timisoara", "iasi", "brasov", "sibiu", "constanta"] },
  { code: "RS", name: "Serbia", currency: "RSD", region: "Europe",
    aliases: ["srbija", "republic of serbia"],
    languages: ["sr", "en"],
    cities: ["belgrade", "beograd", "novi sad", "nis", "kragujevac", "subotica"] },
  { code: "SE", name: "Sweden", currency: "SEK", region: "Europe",
    aliases: ["sverige"],
    languages: ["sv", "en"],
    cities: ["stockholm", "gothenburg", "goteborg", "göteborg", "malmo", "malmö", "uppsala", "linkoping", "lund", "vasteras"] },
  { code: "SI", name: "Slovenia", currency: "EUR", region: "Europe",
    aliases: ["slovenija"],
    languages: ["sl", "en"],
    cities: ["ljubljana", "maribor", "celje", "kranj", "koper"] },
  { code: "SK", name: "Slovakia", currency: "EUR", region: "Europe",
    aliases: ["slovensko", "slovak republic"],
    languages: ["sk", "en"],
    cities: ["bratislava", "kosice", "košice", "zilina", "nitra", "banska bystrica", "presov", "trnava"] },
  { code: "TR", name: "Turkey", currency: "TRY", region: "Europe",
    aliases: ["turkiye", "türkiye", "republic of turkey"],
    languages: ["tr", "en"],
    cities: ["istanbul", "ankara", "izmir", "bursa", "antalya", "konya", "adana"] },
  { code: "UA", name: "Ukraine", currency: "UAH", region: "Europe",
    aliases: ["ukraina", "ukrayina"],
    languages: ["uk", "en"],
    cities: ["kyiv", "kiev", "lviv", "kharkiv", "odesa", "odessa", "dnipro", "vinnytsia"] },

  // ─── North America ─────────────────────────────────────────────────────────
  { code: "CA", name: "Canada", currency: "CAD", region: "North America",
    aliases: ["can"],
    languages: ["en", "fr"],
    cities: ["toronto", "vancouver", "montreal", "montréal", "calgary", "ottawa", "edmonton", "waterloo", "quebec city", "halifax"] },
  { code: "MX", name: "Mexico", currency: "MXN", region: "North America",
    aliases: ["méxico", "estados unidos mexicanos"],
    languages: ["es", "en"],
    cities: ["mexico city", "ciudad de mexico", "guadalajara", "monterrey", "queretaro", "puebla", "tijuana", "merida"] },
  { code: "US", name: "United States", currency: "USD", region: "North America",
    aliases: ["usa", "united states of america", "u s a"],
    languages: ["en"],
    cities: ["new york", "san francisco", "los angeles", "seattle", "austin", "chicago", "boston", "denver", "atlanta", "dallas", "san jose", "washington"] },

  // ─── South America ─────────────────────────────────────────────────────────
  { code: "AR", name: "Argentina", currency: "ARS", region: "South America",
    aliases: ["argentine republic"],
    languages: ["es", "en"],
    cities: ["buenos aires", "cordoba", "córdoba", "rosario", "mendoza", "la plata", "mar del plata", "san miguel de tucuman"] },
  { code: "BR", name: "Brazil", currency: "BRL", region: "South America",
    aliases: ["brasil"],
    languages: ["pt", "en"],
    cities: ["sao paulo", "são paulo", "rio de janeiro", "belo horizonte", "brasilia", "curitiba", "porto alegre", "recife", "florianopolis", "campinas"] },
  { code: "CL", name: "Chile", currency: "CLP", region: "South America",
    aliases: ["republic of chile"],
    languages: ["es", "en"],
    cities: ["santiago", "valparaiso", "concepcion", "vina del mar", "antofagasta", "temuco"] },
  { code: "CO", name: "Colombia", currency: "COP", region: "South America",
    aliases: ["republic of colombia"],
    languages: ["es", "en"],
    cities: ["bogota", "bogotá", "medellin", "medellín", "cali", "barranquilla", "cartagena", "bucaramanga", "pereira"] },
  { code: "PE", name: "Peru", currency: "PEN", region: "South America",
    aliases: ["perú"],
    languages: ["es", "en"],
    cities: ["lima", "arequipa", "trujillo", "cusco", "chiclayo", "piura"] },
  { code: "UY", name: "Uruguay", currency: "UYU", region: "South America",
    aliases: ["oriental republic of uruguay"],
    languages: ["es", "en"],
    cities: ["montevideo", "punta del este", "maldonado", "ciudad de la costa", "las piedras"] },

  // ─── Asia ──────────────────────────────────────────────────────────────────
  { code: "AE", name: "United Arab Emirates", currency: "AED", region: "Asia",
    aliases: ["uae", "emirates"],
    languages: ["ar", "en"],
    cities: ["dubai", "abu dhabi", "sharjah", "ajman", "ras al khaimah", "fujairah"] },
  { code: "BD", name: "Bangladesh", currency: "BDT", region: "Asia",
    aliases: ["peoples republic of bangladesh"],
    languages: ["bn", "en"],
    cities: ["dhaka", "chittagong", "chattogram", "sylhet", "khulna", "rajshahi"] },
  { code: "CN", name: "China", currency: "CNY", region: "Asia",
    aliases: ["prc", "peoples republic of china", "mainland china"],
    languages: ["zh", "en"],
    cities: ["beijing", "shanghai", "shenzhen", "guangzhou", "hangzhou", "chengdu", "wuhan", "xian", "nanjing", "suzhou"] },
  { code: "HK", name: "Hong Kong", currency: "HKD", region: "Asia",
    aliases: ["hongkong", "hong kong sar"],
    languages: ["zh", "en"],
    cities: ["kowloon", "tsim sha tsui", "sha tin", "wan chai", "kwun tong", "causeway bay"] },
  { code: "ID", name: "Indonesia", currency: "IDR", region: "Asia",
    aliases: ["republic of indonesia"],
    languages: ["id", "en"],
    cities: ["jakarta", "bandung", "surabaya", "yogyakarta", "medan", "semarang", "denpasar", "bali"] },
  { code: "IL", name: "Israel", currency: "ILS", region: "Asia",
    aliases: ["state of israel"],
    languages: ["he", "en"],
    cities: ["tel aviv", "jerusalem", "haifa", "herzliya", "ramat gan", "beer sheva", "netanya"] },
  { code: "IN", name: "India", currency: "INR", region: "Asia",
    aliases: ["bharat", "republic of india"],
    languages: ["en", "hi"],
    cities: ["mumbai", "bangalore", "bengaluru", "delhi", "new delhi", "hyderabad", "pune", "chennai", "kolkata", "noida", "gurgaon", "ahmedabad"] },
  { code: "JP", name: "Japan", currency: "JPY", region: "Asia",
    aliases: ["nippon", "nihon"],
    languages: ["ja", "en"],
    cities: ["tokyo", "osaka", "yokohama", "nagoya", "fukuoka", "kyoto", "sapporo", "kobe"] },
  { code: "KR", name: "South Korea", currency: "KRW", region: "Asia",
    aliases: ["korea", "republic of korea", "hanguk"],
    languages: ["ko", "en"],
    cities: ["seoul", "busan", "incheon", "daegu", "daejeon", "gwangju", "seongnam", "pangyo"] },
  { code: "MY", name: "Malaysia", currency: "MYR", region: "Asia",
    aliases: ["malaysia truly asia"],
    languages: ["ms", "en"],
    cities: ["kuala lumpur", "penang", "johor bahru", "cyberjaya", "petaling jaya", "shah alam", "ipoh"] },
  { code: "PH", name: "Philippines", currency: "PHP", region: "Asia",
    aliases: ["the philippines", "pilipinas"],
    languages: ["en", "tl"],
    cities: ["manila", "makati", "quezon city", "cebu", "taguig", "davao", "pasig"] },
  { code: "PK", name: "Pakistan", currency: "PKR", region: "Asia",
    aliases: ["islamic republic of pakistan"],
    languages: ["en", "ur"],
    cities: ["karachi", "lahore", "islamabad", "rawalpindi", "faisalabad", "peshawar", "multan"] },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", region: "Asia",
    aliases: ["ksa", "kingdom of saudi arabia"],
    languages: ["ar", "en"],
    cities: ["riyadh", "jeddah", "dammam", "mecca", "medina", "al khobar"] },
  { code: "SG", name: "Singapore", currency: "SGD", region: "Asia",
    aliases: ["republic of singapore"],
    languages: ["en", "zh"],
    cities: ["jurong", "tampines", "changi", "woodlands", "one north"] },
  { code: "TH", name: "Thailand", currency: "THB", region: "Asia",
    aliases: ["kingdom of thailand"],
    languages: ["th", "en"],
    cities: ["bangkok", "chiang mai", "phuket", "pattaya", "khon kaen", "nonthaburi"] },
  { code: "TW", name: "Taiwan", currency: "TWD", region: "Asia",
    aliases: ["republic of china", "chinese taipei"],
    languages: ["zh", "en"],
    cities: ["taipei", "new taipei", "taichung", "kaohsiung", "tainan", "hsinchu"] },
  { code: "VN", name: "Vietnam", currency: "VND", region: "Asia",
    aliases: ["viet nam", "socialist republic of vietnam"],
    languages: ["vi", "en"],
    cities: ["ho chi minh city", "saigon", "hanoi", "da nang", "hai phong", "can tho", "nha trang"] },

  // ─── Africa ────────────────────────────────────────────────────────────────
  { code: "EG", name: "Egypt", currency: "EGP", region: "Africa",
    aliases: ["arab republic of egypt", "misr"],
    languages: ["ar", "en"],
    cities: ["cairo", "alexandria", "giza", "new cairo", "port said", "luxor", "aswan"] },
  { code: "KE", name: "Kenya", currency: "KES", region: "Africa",
    aliases: ["republic of kenya"],
    languages: ["en", "sw"],
    cities: ["nairobi", "mombasa", "kisumu", "nakuru", "eldoret", "thika"] },
  { code: "MA", name: "Morocco", currency: "MAD", region: "Africa",
    aliases: ["maroc", "kingdom of morocco"],
    languages: ["ar", "fr"],
    cities: ["casablanca", "rabat", "marrakech", "tangier", "fez", "agadir", "kenitra"] },
  { code: "NG", name: "Nigeria", currency: "NGN", region: "Africa",
    aliases: ["federal republic of nigeria"],
    languages: ["en"],
    cities: ["lagos", "abuja", "ibadan", "port harcourt", "kano", "benin city", "enugu"] },
  { code: "ZA", name: "South Africa", currency: "ZAR", region: "Africa",
    aliases: ["rsa", "republic of south africa", "suid afrika"],
    languages: ["en", "af"],
    cities: ["johannesburg", "cape town", "durban", "pretoria", "port elizabeth", "stellenbosch", "centurion", "sandton"] },

  // ─── Oceania ───────────────────────────────────────────────────────────────
  { code: "AU", name: "Australia", currency: "AUD", region: "Oceania",
    aliases: ["commonwealth of australia"],
    languages: ["en"],
    cities: ["sydney", "melbourne", "brisbane", "perth", "adelaide", "canberra", "gold coast", "hobart"] },
  { code: "NZ", name: "New Zealand", currency: "NZD", region: "Oceania",
    aliases: ["aotearoa"],
    languages: ["en"],
    cities: ["auckland", "wellington", "christchurch", "hamilton", "dunedin", "tauranga"] },
];
